### ISSUE TITLE
Individual shoutout pages just display a blank ElggObject

### ISSUE THREAD

**Issue by mrclay** [kevinjardine/shoutout#4] opened 2012-01-10 21:13 UTC

**Comment by kevinjardine** [comment] 2012-01-11 15:26
I can't reproduce this with the new code on my development server.
The url format should be:

shoutout/view/guid

and that works for me.

I will try on the UFL site.

**Comment by mrclay** [comment] 2012-01-11 16:05
the pages probably exist, but the "+1 more" links to them are wrong. Is there a registered entity URL hander?

**Comment by kevinjardine** [comment] 2012-01-11 16:56
There was a URL handler but the line to register it was missing from the init function. It is fixed on the development site now and I'll upload it to github later.

**Closed as completed by kevinjardine** 2012-01-11 16:56 UTC
